### ISSUE TITLE
PARSE : ArrayIndexOutOfBoundsException at AINameParserClassifier.fitParsedName(AINameParserClassifier.java:178)

### ISSUE THREAD

**Issue by namsor** [namsor/namsor-tools-v2#9]
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.namsor.api2.classify.AINameParserClassifier.fitParsedName(AINameParserClassifier.java:178)
        at com.namsor.api2.classify.AINameParserClassifier.fitParsedName(AINameParserClassifier.java:226)
        at com.namsor.api2.classify.AI.predictParserType(AI.java:643)
        at com.namsor.api2.NamSorAPI2.parseNameBatch(NamSorAPI2.java:3267)

**Comment by namsor** [comment]
Input : 
41368/B. Al Otabi|Al Otabi

**Comment by namsor** [comment]
Fixed with v2.0.10
